stages:
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/utils.py
      - data/winequality-red.csv
    outs:
      - models/wine_model.pkl
      - reports/metrics.json
      - reports/model_comparison.png
      - reports/actual_vs_predicted.png
